# Generated by Django 4.1.3 on 2022-11-22 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiFamilia', '0002_familiar1_familiar2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar1',
        ),
        migrations.DeleteModel(
            name='Familiar2',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_cumpleanios',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 20, 46, 24, 65797)),
        ),
    ]
