# Generated by Django 4.1.3 on 2022-11-22 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiFamilia', '0003_delete_familiar1_delete_familiar2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 20, 48, 8, 762484)),
        ),
    ]
