# Generated by Django 4.1.3 on 2022-11-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiFamilia', '0004_alter_familiar_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha',
        ),
    ]
